### ISSUE TITLE
AirMap PID:5640 error

### ISSUE THREAD

**Issue by the-lotuseater** [airmap/AirMapSDK-Android#11]
error log-
`Process: com.example.skymap, PID: 5640
    java.lang.NullPointerException: value for name x-Api-Key == null
        at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:348)
        at okhttp3.Headers$Builder.add(Headers.java:290)
        at okhttp3.Request$Builder.addHeader(Request.java:196)
        at com.airmap.airmapsdk.ui.views.AirMapMapView$2.intercept(AirMapMapView.java:159)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

Please look into this!

**Comment by vanshg** [comment]
Seems from the error message that the API key provided was null. Do you have the API key defined in your `airmap.config.json` file?

**Comment by the-lotuseater** [comment]
Yes I have the MapBox access token and AirMap access key in the config file.
